spring:
  application:
    name: cafe-api

  cache:
    type: redis
    redis:
      time-to-live: 60s

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s
      connect-timeout: 2s

  datasource:
    url: jdbc:mysql://localhost:3306/cafe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&sessionVariables=innodb_lock_wait_timeout=3
    username: cafeuser
    password: cafepw1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

