spring:
  application:
    name: cafe-api

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/cafe?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: cafeuser
    password: cafepw1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

